### ISSUE TITLE
Error in IE8 - No such interface supported

### ISSUE THREAD

**Issue by fruitbatinshades** [daepark/postmessage#2]
94     if (("postMessage" in target) && !o.hash) {
95              pm._bind();
96             target.postMessage(JSON.stringify(msg), o.origin || '*');
97     }

In IE8 I get the following error in the above code.

No such interface supported

on line 96. All the variables are populated as I would expect

msg = {value:'result'}
o.origin = "*"

/\* Calling code - works in all other browsers */
pm({
     target: window.opener,
     type: "getValue",
     url: window.opener.location,
     data: {
        value: $(e.target).text()
      })

Any ideas what could be wrong?

**Comment by fruitbatinshades** [comment]
I can supply a url(via email) if you can help

**Comment by daepark** [comment]
Are you able to run the qunit tests on postmessage.freebaseapps.com with your browser? I just ran them successfully with IE8 Version 8.0.6001.18702. Can you please list what version of IE you are using by going to Help->About Internet Explorer?

**Comment by daepark** [comment]
I think I tracked down the issues. In IE8, postMessage only works for IFRAMES/FRAMES: http://bit.ly/9U4Fsg

**Comment by daepark** [comment]
I guess the work around is to force using location hash polling if you are working using window.opener and IE8 

pm({..., hash:true})
pm.bind(..., true)

Or use window.frames[] and window.parent.

**Comment by fruitbatinshades** [comment]
That looks like it! Will try and figure out how to use the hashes

**Comment by topliceanu** [comment]
It would seem that PM is working on IE8 only until you open a popup window. I have PM working perfectly using window.frames[] and window.parent; then, after i open a facebook login popup, PM stops working, triggering the same error as above.
